# Bastion configuration
#
# Logout Timer = How long should it take for a player to safelog
# Combat-tag - Attacker = How long should the attacking player be combat tagged for
# Combat-tag - Attacked = How long should the attacked player be combat tagged for
# PvP Protection - Enabled = Should players receive PvP protection upon logging in for the first time or returning from a deathban?
# PvP Protection - Duration = How long (in seconds) should a player be given PvP protection for?
# PvP Safety - Enabled = Should players be protected upon changing worlds?
# PvP Safety - Duration = How long should players be protected for upon changing worlds?
bastion:
  logout-timer: 30
  combat-tag:
    attacker: 60
    attacked: 30
  pvp-protection:
    enabled: true
    duration: 1800
  pvp-safety:
    enabled: true
    duration: 5

# Class configuration
classes:
  archer:
    enabled: true
  scout:
    enabled: true
  bard:
    enabled: true

# Deathbans configuration
#
# Enabled = Should deathbans be enabled on this server?
# Normal-db = Typical deathban for a player who has over 1 hour of playtime and they did not die in an event
# Event-db = Deathban players receive upon dying in an event claim that is running an active event
# New-db = Deathban new players receive (less than 1hr playtime)
deathbans:
  enabled: true
  normal-db: 86400
  event-db: 10800
  new-db: 3600

# Lives configuration
#
# Enabled = Should lives be enabled on this server?
# Revives-enabled = Should players be able to /revive others on this server?
lives:
  enabled: true
  revives-enabled: true

# Mechanics configuration
#
# Emerald-xp = Should players be able to convert emeralds in to EXP bottles?
# Enderpearl-cooldown = Should enderpearls be put on lock when a player uses them?
# Mobstacking = Should large groups of nearby mobs be grouped together in to stacks?
mechanics:
  emerald-xp:
    enabled: true
  enderpearl-cooldowns:
    enabled: true
    duration: 16
  mobstacking:
    enabled: true
    max-stack: 30
    merge-interval: 5

# Mining mechanics
#
# Enabled = Should RevivalMining be enabled?
# Values - Pool = What number pool should we pick from?
# Values - Gold = What number should the pool have to land under for gold to spawn?
# Values - Diamond = What number should the pool have to land under for diamond to spawn?
# Values - Emerald = What number should the pool have to land under for emerald to spawn?
# Announce - Should finding this ore cause an announcement?
mining:
  enabled: true
  values:
    pool: 10000
    gold:
      announce: false
      pool: 300
    diamond:
      announce: true
      pool: 200
    emerald:
      announce: true
      pool: 100

# Progression configuration
#
# Enabled = Should progression be enabled on this server?
# Duration = How long should a player have to play in order to fill out their progression?
progression:
  enabled: true
  duration: 3600