name: FactionsCore
main: gg.revival.factions.core.FC
version: 1.0.0
author: johnsama
description: Powers HCFR's Spawntag, Cooldowns, Deathbans, Lives, Progression and Scoreboards
depends: [Revival]
commands:
  logout:
    description: Safely logout from the server without leaving a Combat Logger
    aliases: [safelog]
  crowbar:
    description: Spawn a crowbar
  pvp:
    description: PvP protection command
  deathban:
    description: Deathban command
  deaths:
    description: View a players previous deathbans
  events:
    description: Events command
    aliases: [e, event, koth, dtc, beacon, palace, citadel, conquest]
  lives:
    description: Lives command
    aliases: [live, lifes, life]
  revive:
    description: Revive command
  spawn:
    description: Spawn command
  end:
    description: End command
  endexit:
    description: End Exit command
  progression:
    description: Progression command
    aliases: [progress, p]