name: FactionsCore
main: gg.revival.factions.core.FC
version: 1.0.0
author: johnsama
description: Powers Timers, Classes, Essentials, Deathbans, Events, Mechanic Changes, Locations, Mining, Progression, yada yada
depends: [Revival]
commands:
  factionscore:
    description: Core functions command
    aliases: [fc, fcore]
  logout:
    description: Safely logout from the server without leaving a Combat Logger
    aliases: [safelog]
  crowbar:
    description: Spawn a crowbar
  pvp:
    description: PvP protection command
  deathban:
    description: Deathban command
  deaths:
    description: View a players previous deathbans
  events:
    description: Events command
    aliases: [e, event]
  tables:
    description: Table command
    aliases: [table, loottables, loot]
  lives:
    description: Lives command
    aliases: [live, lifes, life]
  revive:
    description: Revive command
  spawn:
    description: Spawn command
  end:
    description: End command
  endexit:
    description: End Exit command
  progression:
    description: Progression command
    aliases: [progress, p]
  statistics:
    description: Stats command
    aliases: [stats, ores, playtime, kd]
  servermode:
    description: Server mode command
    aliases: [sm, mode]